version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 --debug --log-level debug --scope hub
  proverbs-for-code-backend:
    image: jaywhy13/proverbs-for-code-backend
    env_file: .env/proverbs-for-code-backend
    ports:
      - 3001:3001
    labels:
      - "com.centurylinklabs.watchtower.scope=hub"
