version: "2"
services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 3600 --debug --log-level debug --scope hub
  proxy:
    image: nginxproxy/nginx-proxy:1.5
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  proverbs-for-code-backend:
    image: jaywhy13/proverbs-for-code-backend
    env_file: .env/proverbs-for-code-backend
    ports:
      - 3001:3001
    labels:
      - "com.centurylinklabs.watchtower.scope=hub"
    platform: linux/amd64
  proverbs-for-code:
    image: jaywhy13/proverbs-for-code
    ports:
      - 3002:80
    labels:
      - "com.centurylinklabs.watchtower.scope=hub"
    platform: linux/amd64
    environment:
      - VIRTUAL_HOST=proverbs.hub.me
